- name: Deploy Node.js App from DockerHub on Localhost (WSL)
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: tejasparab17/node-app
        source: pull

    - name: Run Docker container
      docker_container:
        name: nodeapp
        image: tejasparab17/node-app
        state: started
        restart_policy: always
        ports:
          - "3000:3000"

